fn main() {
    // Bundle the gettext `.po` translations under `lang/` so the UI's `@tr(...)`
    // strings can switch language at runtime via slint::select_bundled_translation.
    // The `.slint` source (msgids) is English; `lang/zh/LC_MESSAGES/rudder.po`
    // maps msgids to Chinese and `lang/en/...` keeps the identity mapping.  No
    // per-component context, so msgids are the raw English strings.
    println!("cargo:rerun-if-changed=lang");
    slint_build::compile_with_config(
        "ui/app.slint",
        slint_build::CompilerConfiguration::new()
            .with_style("fluent".into())
            .with_bundled_translations("lang")
            .with_default_translation_context(slint_build::DefaultTranslationContext::None),
    )
    .expect("Slint build failed");

    // Embed the application icon into the Windows executable so it shows up in
    // Explorer, the taskbar and shortcuts. No-op on non-Windows targets.
    #[cfg(windows)]
    {
        println!("cargo:rerun-if-changed=assets/rudder.ico");
        println!("cargo:rerun-if-changed=assets/rudder.exe.manifest");
        let mut res = winresource::WindowsResource::new();
        res.set_icon("assets/rudder.ico");
        // Embed an application manifest declaring Per-Monitor DPI Awareness V2.
        // Without it the DPI-awareness level depends on winit's runtime
        // SetProcessDpiAwarenessContext call, which races: if anything touches a
        // DPI API first the call silently fails and the window jumps in size /
        // cursor offset when dragged across monitors with different scaling (#194).
        // The manifest is authoritative and applied before any code runs.
        res.set_manifest_file("assets/rudder.exe.manifest");
        if let Err(e) = res.compile() {
            println!("cargo:warning=failed to embed Windows icon: {e}");
        }
    }

    // --- Embed resolved dependency versions for the About dialog -----------
    generate_dep_versions();
}

/// Parse Cargo.lock, extract every `[[package]]` name + version pair
/// (all resolved deps, not just direct ones), and write them into a
/// generated Rust source file that the app includes at compile time.
fn generate_dep_versions() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let lock_path = std::path::Path::new(&manifest_dir).join("Cargo.lock");
    println!("cargo:rerun-if-changed={}", lock_path.display());

    let lock = std::fs::read_to_string(&lock_path).unwrap_or_else(|e| {
        println!("cargo:warning=cannot read Cargo.lock: {e}");
        String::new()
    });

    let deps: Vec<(String, String)> = parse_lock_packages(&lock);

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest = std::path::Path::new(&out_dir).join("deps.rs");
    let mut f = std::fs::File::create(dest).expect("create deps.rs");

    use std::io::Write as _;
    writeln!(f, "// Generated by build.rs — DO NOT EDIT").unwrap();
    writeln!(f, "pub(crate) const DEP_VERSIONS: &[(&str, &str)] = &[").unwrap();
    for (name, version) in &deps {
        writeln!(f, r#"    ("{name}", "{version}"),"#).unwrap();
    }
    writeln!(f, "];").unwrap();
}

/// Minimal Cargo.lock parser — each `[[package]]` block has `name` and
/// `version` keys on the following lines.  We only need those two fields.
fn parse_lock_packages(lock: &str) -> Vec<(String, String)> {
    let mut deps = Vec::new();
    let mut name = String::new();
    let mut version = String::new();

    for line in lock.lines() {
        if line.trim() == "[[package]]" {
            if !name.is_empty() {
                deps.push((std::mem::take(&mut name), std::mem::take(&mut version)));
            }
        } else if let Some(v) = line.trim().strip_prefix("name = ") {
            name = v.trim().trim_matches('"').to_string();
        } else if let Some(v) = line.trim().strip_prefix("version = ") {
            version = v.trim().trim_matches('"').to_string();
        }
    }
    if !name.is_empty() {
        deps.push((name, version));
    }
    deps
}
